-- AlterTable
ALTER TABLE "productPurchases" ALTER COLUMN "createdBy" DROP DEFAULT,
ALTER COLUMN "createdBy" SET DATA TYPE TEXT,
ALTER COLUMN "deletedBy" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "productSales" ALTER COLUMN "createdBy" DROP DEFAULT,
ALTER COLUMN "createdBy" SET DATA TYPE TEXT,
ALTER COLUMN "deletedBy" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "products" ALTER COLUMN "createdBy" DROP DEFAULT,
ALTER COLUMN "createdBy" SET DATA TYPE TEXT,
ALTER COLUMN "deletedBy" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "purchases" ALTER COLUMN "createdBy" DROP DEFAULT,
ALTER COLUMN "createdBy" SET DATA TYPE TEXT,
ALTER COLUMN "deletedBy" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "roles" ALTER COLUMN "createdBy" DROP DEFAULT,
ALTER COLUMN "createdBy" SET DATA TYPE TEXT,
ALTER COLUMN "deletedBy" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "sales" ALTER COLUMN "createdBy" DROP DEFAULT,
ALTER COLUMN "createdBy" SET DATA TYPE TEXT,
ALTER COLUMN "deletedBy" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "createdBy" DROP DEFAULT,
ALTER COLUMN "createdBy" SET DATA TYPE TEXT,
ALTER COLUMN "deletedBy" SET DATA TYPE TEXT;
